{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.9.0)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module Majom.Vision.Vision where
import Prelude ( Bool(..), Enum, Double, String, Maybe(..),
                 Eq, Show, Ord,
                 return, length, IO, fromIntegral, fromEnum, toEnum,
                 (.), (&&), (||), (==), (++), ($), (-) )

import Control.Exception
import Data.ByteString.Lazy
import Data.Hashable
import Data.Int
import Data.Text.Lazy ( Text )
import qualified Data.Text.Lazy as TL
import Data.Typeable ( Typeable )
import qualified Data.HashMap.Strict as Map
import qualified Data.HashSet as Set
import qualified Data.Vector as Vector

import Thrift
import Thrift.Types ()


import Majom.Vision.Vision_Types
import qualified Majom.Vision.Vision_Iface as Iface
-- HELPER FUNCTIONS AND STRUCTURES --

data Observe_args = Observe_args deriving (Show,Eq,Typeable)
instance Hashable Observe_args where
  hashWithSalt salt record = salt  
write_Observe_args oprot record = do
  writeStructBegin oprot "Observe_args"
  writeFieldStop oprot
  writeStructEnd oprot
read_Observe_args_fields iprot record = do
  (_,_t8,_id9) <- readFieldBegin iprot
  if _t8 == T_STOP then return record else
    case _id9 of 
      _ -> do
        skip iprot _t8
        readFieldEnd iprot
        read_Observe_args_fields iprot record
read_Observe_args iprot = do
  _ <- readStructBegin iprot
  record <- read_Observe_args_fields iprot (Observe_args{})
  readStructEnd iprot
  return record
data Observe_result = Observe_result{f_Observe_result_success :: Maybe Position} deriving (Show,Eq,Typeable)
instance Hashable Observe_result where
  hashWithSalt salt record = salt   `hashWithSalt` f_Observe_result_success record  
write_Observe_result oprot record = do
  writeStructBegin oprot "Observe_result"
  case f_Observe_result_success record of {Nothing -> return (); Just _v -> do
    writeFieldBegin oprot ("success",T_STRUCT,0)
    write_Position oprot _v
    writeFieldEnd oprot}
  writeFieldStop oprot
  writeStructEnd oprot
read_Observe_result_fields iprot record = do
  (_,_t13,_id14) <- readFieldBegin iprot
  if _t13 == T_STOP then return record else
    case _id14 of 
      0 -> if _t13 == T_STRUCT then do
        s <- (read_Position iprot)
        read_Observe_result_fields iprot record{f_Observe_result_success=Just s}
        else do
          skip iprot _t13
          read_Observe_result_fields iprot record
      _ -> do
        skip iprot _t13
        readFieldEnd iprot
        read_Observe_result_fields iprot record
read_Observe_result iprot = do
  _ <- readStructBegin iprot
  record <- read_Observe_result_fields iprot (Observe_result{f_Observe_result_success=Nothing})
  readStructEnd iprot
  return record
process_observe (seqid, iprot, oprot, handler) = do
  args <- read_Observe_args iprot
  readMessageEnd iprot
  rs <- return (Observe_result Nothing)
  res <- (do
    res <- Iface.observe handler
    return rs{f_Observe_result_success= Just res})
  writeMessageBegin oprot ("observe", M_REPLY, seqid);
  write_Observe_result oprot res
  writeMessageEnd oprot
  tFlush (getTransport oprot)
proc_ handler (iprot,oprot) (name,typ,seqid) = case name of
  "observe" -> process_observe (seqid,iprot,oprot,handler)
  _ -> do
    skip iprot T_STRUCT
    readMessageEnd iprot
    writeMessageBegin oprot (name,M_EXCEPTION,seqid)
    writeAppExn oprot (AppExn AE_UNKNOWN_METHOD ("Unknown function " ++ TL.unpack name))
    writeMessageEnd oprot
    tFlush (getTransport oprot)
process handler (iprot, oprot) = do
  (name, typ, seqid) <- readMessageBegin iprot
  proc_ handler (iprot,oprot) (name,typ,seqid)
  return True
